name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.2
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Wait for MongoDB
      run: |
        echo "Waiting for MongoDB to be ready..."
        for i in {1..30}; do
          if echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet; then
            echo "MongoDB is ready!"
            exit 0
          fi
          echo "Attempt $i/30: MongoDB not ready yet..."
          sleep 2
        done
        echo "Error: MongoDB failed to become ready"
        exit 1
        
    - name: Run tests
      env:
        MONGODB_URI: mongodb://localhost:27017/beehive_test
        SECRET_KEY: beehive_test
        TESTING: true
        GOOGLE_CLIENT_ID: dummy-client-id
        GOOGLE_CLIENT_SECRET: dummy-client-secret
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v --cov=app --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 