name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.2
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install MongoDB Client
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-shell
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Wait for MongoDB
      run: |
        echo "Waiting for MongoDB to be ready..."
        for i in {1..30}; do
          if mongo --eval "db.runCommand('ping').ok" localhost:27017/test --quiet; then
            echo "MongoDB is ready!"
            exit 0
          fi
          echo "Attempt $i/30: MongoDB not ready yet..."
          sleep 2
        done
        echo "Error: MongoDB failed to become ready"
        exit 1
        
    - name: Run tests
      env:
        MONGODB_URI: mongodb://localhost:27017/beehive_test
        SECRET_KEY: beehive_test
        TESTING: true
        GOOGLE_CLIENT_ID: dummy-client-id
        GOOGLE_CLIENT_SECRET: dummy-client-secret
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v --cov=app --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 